"""Wallet architecture v2 - users transactions webhook events

Revision ID: 4cca1e924c1d
Revises: c6c6cf076044
Create Date: 2026-07-16 11:26:26.241768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cca1e924c1d'
down_revision: Union[str, Sequence[str], None] = 'c6c6cf076044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhook_events',
    sa.Column('monnify_reference', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_webhook_events_id'), 'processed_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_processed_webhook_events_monnify_reference'), 'processed_webhook_events', ['monnify_reference'], unique=True)
    op.create_table('transactions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_group_id'), 'transactions', ['group_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('wallet_balance', sa.Numeric(precision=18, scale=2), nullable=False))
    op.add_column('users', sa.Column('personal_reserved_account_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('personal_reserved_account_bank', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('personal_reserved_account_reference', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'personal_reserved_account_reference')
    op.drop_column('users', 'personal_reserved_account_bank')
    op.drop_column('users', 'personal_reserved_account_number')
    op.drop_column('users', 'wallet_balance')
    op.drop_column('users', 'pin_hash')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_group_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_processed_webhook_events_monnify_reference'), table_name='processed_webhook_events')
    op.drop_index(op.f('ix_processed_webhook_events_id'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    # ### end Alembic commands ###
