"""Add personal_reserved_account_name to users

Revision ID: 603bbdd967ab
Revises: 8feaaa7db56f
Create Date: 2026-07-16 12:35:35.581457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603bbdd967ab'
down_revision: Union[str, Sequence[str], None] = '8feaaa7db56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personal_reserved_account_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personal_reserved_account_name')
    # ### end Alembic commands ###
