"""Add kyc_status and has_wallet to users

Revision ID: 8feaaa7db56f
Revises: 65cd441e2216
Create Date: 2026-07-16 12:04:42.655476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8feaaa7db56f'
down_revision: Union[str, Sequence[str], None] = '65cd441e2216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_status', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('has_wallet', sa.Boolean(), nullable=False))
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('users', 'has_wallet')
    op.drop_column('users', 'kyc_status')
    # ### end Alembic commands ###
