"""Add auto_debit to Membership

Revision ID: c9cf5ffeb7d9
Revises: 7bbf5ddfdc33
Create Date: 2026-07-19 08:55:11.749736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cf5ffeb7d9'
down_revision: Union[str, Sequence[str], None] = '7bbf5ddfdc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('auto_debit_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('memberships', sa.Column('auto_debit_days_before', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'auto_debit_days_before')
    op.drop_column('memberships', 'auto_debit_enabled')
    # ### end Alembic commands ###
