"""Update Group and Membership schemas to PRD v5

Revision ID: cac1a4782411
Revises: 603bbdd967ab
Create Date: 2026-07-16 20:08:44.960780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac1a4782411'
down_revision: Union[str, Sequence[str], None] = '603bbdd967ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('cycle_frequency', sa.String(length=50), nullable=False))
    op.add_column('groups', sa.Column('payout_day_of_week', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('payout_day_of_month', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('payout_month', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('payout_day_override', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('requires_approval_for_delegate', sa.Boolean(), nullable=False))
    op.add_column('groups', sa.Column('requires_approval_for_swap', sa.Boolean(), nullable=False))
    op.add_column('groups', sa.Column('invite_code', sa.String(length=10), nullable=True))
    op.add_column('groups', sa.Column('invite_code_active', sa.Boolean(), nullable=False))
    op.add_column('groups', sa.Column('pool_balance', sa.Float(), nullable=False))
    op.add_column('groups', sa.Column('member_cap', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_groups_invite_code'), 'groups', ['invite_code'], unique=True)
    op.drop_column('groups', 'cycle_length_days')
    op.drop_column('groups', 'payout_day_offset')
    op.add_column('memberships', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('memberships', 'reserved_account_bank')
    op.drop_column('memberships', 'reserved_account_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('reserved_account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('memberships', sa.Column('reserved_account_bank', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('memberships', 'is_admin')
    op.add_column('groups', sa.Column('payout_day_offset', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('cycle_length_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_groups_invite_code'), table_name='groups')
    op.drop_column('groups', 'member_cap')
    op.drop_column('groups', 'pool_balance')
    op.drop_column('groups', 'invite_code_active')
    op.drop_column('groups', 'invite_code')
    op.drop_column('groups', 'requires_approval_for_swap')
    op.drop_column('groups', 'requires_approval_for_delegate')
    op.drop_column('groups', 'payout_day_override')
    op.drop_column('groups', 'payout_month')
    op.drop_column('groups', 'payout_day_of_month')
    op.drop_column('groups', 'payout_day_of_week')
    op.drop_column('groups', 'cycle_frequency')
    # ### end Alembic commands ###
