// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcnRwA6IMPXsrSOAJNYVbq0_OjDjo4UNA',
    appId: '1:225154355801:web:05af83a675eba956779748',
    messagingSenderId: '225154355801',
    projectId: 'agrohive-1107d',
    authDomain: 'agrohive-1107d.firebaseapp.com',
    storageBucket: 'agrohive-1107d.firebasestorage.app',
    measurementId: 'G-H9QCTRXHG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuul2DDTm0RqE8mpyRx8Y1-OxYBl-48bQ',
    appId: '1:225154355801:android:4048ee1da57f2b9f779748',
    messagingSenderId: '225154355801',
    projectId: 'agrohive-1107d',
    storageBucket: 'agrohive-1107d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6yI3Ws-rKMBs_mSNRml5O0uJP70RizM',
    appId: '1:225154355801:ios:e5ffb1002810b781779748',
    messagingSenderId: '225154355801',
    projectId: 'agrohive-1107d',
    storageBucket: 'agrohive-1107d.firebasestorage.app',
    iosBundleId: 'com.example.payajo',
  );
}
